"""Summarize completed source-DLL checks without committing logs or historical DLLs."""
import hashlib
import json
import subprocess
from collections import defaultdict
from pathlib import Path

root = Path(__file__).resolve().parents[2]
def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()
def read(path):
    return json.loads((root / path).read_text(encoding="utf-8-sig"))
reports = {}
for name, path in [("balance", ".tmp/balance-check.json"), ("native_ui", ".tmp/balance-ui.json"), ("inventory", ".tmp/balance-inventory.json")]:
    report = read(path)
    cases = report if isinstance(report, list) else report.get("checks", report.get("cases"))
    groups = defaultdict(lambda: {"count": 0, "passed": 0})
    for case in cases:
        group = groups[case["Name"].split("/")[0]]
        group["count"] += 1
        group["passed"] += int(case["Ok"])
    failures = [c for c in cases if not c["Ok"]]
    assert not failures, (name, failures)
    reports[name] = {"count": len(cases), "passed": len(cases), "failed": 0, "groups": groups,
                     "failures": failures, "full_report_sha256": digest(root / path)}

metadata = read(".tmp/balance-implementation-20260924/legacy/packages.json")
baselines = []
for i, p in enumerate(metadata):
    version = p["metadata"]["Version"]
    fixture = root / "tools/fixtures/balance-20260924" / (version + ".xml.gz")
    baselines.append({"package_file": p["file"], "package_sha256": p["sha256"], "version": version,
                      "api": p["metadata"]["ApiVersion"], "package_name": p["metadata"]["PackageName"],
                      "schema": 6 if i == 0 else 4, "rules": 7 if i == 0 else 2,
                      "dll_sha256": digest(root / f".tmp/balance-implementation-20260924/legacy/{i}/ScCsgoKnives.dll"),
                      "fixture": str(fixture.relative_to(root)).replace("\\", "/"), "fixture_sha256": digest(fixture)})
changed = subprocess.check_output(["git", "diff", "079b42f", "--name-only"], cwd=root, encoding="utf-8").splitlines()
evidence = {
    "date": "2026-09-24", "implementation_base": "079b42f", "scope": "Source build only; no new scmod, installation or player-world access",
    "layout": 5, "schema": 6, "rules": 7,
    "plan_sha256": digest(root / "docs/gun-balance-evidence-2026-09-24.json"),
    "baseline_packages": baselines, "reports": reports,
    "built_dlls": {p: digest(root / p) for p in ["src/ScCsgoKnives/bin/Release/net10.0/ScCsgoKnives.dll", "src/ScCsgoTactical/bin/Release/net10.0/ScCsgoTactical.dll"]},
    "changed_source_sha256": {p: digest(root / p) for p in changed if p.startswith("src/")},
    "limits": ["Synthetic records generated by the actual historical serializers, not player saves", "Windows API 1.9.3.1 host; no Android/full-game acceptance", "No claim of engine power-loss write safety or arbitrary third-party container compatibility", "1.2.0 same-schema update does not trigger automatic schema backup; retain full world and matching old package before installing"]
}
(root / "docs/gun-balance-implementation-evidence-2026-09-24.json").write_text(json.dumps(evidence, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
