"""Regenerates the handle direction table and each knife's handle and blade hulls.

Everything here is in a MESH PART's own space, placed each frame by that part's
binding, because the knife does not stay rigid to the hand bone: the CS:GO
inspects turn the knife in the fingers (the M9's weapon part is 32 degrees off
hand_r at the hold pose, the karambit's 27, the butterfly's 18, and all of them
a hundred and more mid-twirl). A handle direction carried by hand_r therefore
lay a handle on the fist's face that was not the handle being drawn.

Per knife:
  * the handle's direction: the principal axis of the gripped stretch of the
    held part (f - 0.15 .. f + 0.10 along the knife, f = the fraction the fist
    holds), in that part's space. Written into s_handleDirections.
  * the handle hull: that stretch's extreme point in each of 64 directions over
    the sphere, in the part's space. Its deepest point below the fist's face is
    the clearance the box sits off the grip, so the handle's surface rests on
    the face.
  * the blade hull: the same for everything beyond the guard (the blade parts of
    a folding knife, the far stretch of a fixed one). The fist rolls just far
    enough that no blade point sits deeper than the handle does; the guard is
    left out on purpose, the fist grips behind it.
Written to KnifeHulls.cs.
"""
import sys, os, re, math, json, numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rigprobe as R
import gripsolve as G

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RENDERER = os.path.join(ROOT, 'src/ScCsgoKnives/Rendering/CsmcFirstPersonRenderer.cs')
HULLS_CS = os.path.join(ROOT, 'src/ScCsgoKnives/Rendering/KnifeHulls.cs')
HULLS_JSON = os.path.join(ROOT, 'tools/reference/knife_hulls.json')
N_DIRS = 64
HELD_PART = 'weapon_hand_r'
KEEP = {'kukri': (-0.8213, 0.4120, -0.3947), 'push': (0.9692, 0.2251, -0.1000)}

def unit(v): return v / np.linalg.norm(v)

def fibonacci_sphere(n):
    i = np.arange(n) + 0.5
    phi = np.arccos(1 - 2 * i / n); theta = math.pi * (1 + 5 ** 0.5) * i
    return np.c_[np.cos(theta) * np.sin(phi), np.sin(theta) * np.sin(phi), np.cos(phi)]

def hull_of(pts, dirs):
    return np.array([pts[np.argmax(pts @ d)] for d in dirs])

def grip_fractions(cs):
    tbl = cs[cs.index('s_gripOffsets = ['):]; tbl = tbl[:tbl.index('];')]
    return {n: float(f) for n, f in re.findall(r'// (\w+)\s+\((?:solved|shared|claw) f=([\d.]+)', tbl)}

def analyse(name, f):
    kn = G.Knife(name)
    dirs = fibonacci_sphere(N_DIRS)
    blade_parts = [pt for pt in G.MANIFEST[name] if pt.startswith('v_weapon_blade')]
    parts = []
    axis_part = None; axis_whole_deg = None
    for part in G.MANIFEST[name]:
        Vm = G.mesh_part(name, part)                                  # the part's own space
        wb = R.binding_matrix(kn.rig, kn.a, part)
        Pw = (np.c_[Vm, np.ones(len(Vm))] @ wb)[:, :3]                 # rig-pose space at idle
        tf = ((Pw - kn.c) @ kn.ax - kn.lo) / (kn.hi - kn.lo)
        entry = dict(binding=part, handle=[], blade=[])
        if part == HELD_PART:
            held = Vm[(tf > f - 0.15) & (tf < f + 0.10)]
            if len(held) >= 10:
                c = held.mean(0)
                _, _, vt = np.linalg.svd(held - c, full_matrices=False)
                axis = unit(vt[0])
                whole = unit((np.r_[kn.ax, 0] @ np.linalg.inv(wb))[:3])   # the whole knife's axis in this part's space
                if np.dot(axis, whole) < 0: axis = -axis
                axis_part = axis; axis_whole_deg = math.degrees(math.acos(min(1, abs(np.dot(axis, whole)))))
                entry['handle'] = hull_of(held, dirs).tolist()
        if blade_parts:
            if part in blade_parts: entry['blade'] = hull_of(Vm, dirs).tolist()
        else:
            far = Vm[tf > f + 0.25]
            if len(far) >= 10: entry['blade'] = hull_of(far, dirs).tolist()
        if entry['handle'] or entry['blade']: parts.append(entry)
    return dict(axis=None if axis_part is None else axis_part.tolist(), handle_vs_whole_deg=axis_whole_deg, parts=parts)

def write_cs(hulls):
    out = ['using Engine;', '', 'namespace Game;', '',
           '/// <summary>',
           "/// Each knife's handle and blade hulls: the extreme point in each of 64",
           "/// directions over the sphere, per mesh part and in that part's own space, so",
           "/// they follow the part's own binding each frame -- the knife turns in the",
           '/// fingers during an inspect and is not rigid to the hand bone.',
           '/// CsmcFirstPersonRenderer.RestOnFace rests the handle hull on the fist and',
           '/// rolls the fist just far enough to keep the blade hull off it. Generated by',
           '/// tools/knife_hulls.py.',
           '/// </summary>',
           'static class KnifeHulls {',
           '    public readonly struct Part {',
           '        public Part(string binding, Vector3[] handle, Vector3[] blade) { Binding = binding; Handle = handle; Blade = blade; }',
           '        public readonly string Binding;',
           '        public readonly Vector3[] Handle, Blade;',
           '    }',
           '    static readonly Part[][] s_parts = [']
    def block(pts, indent):
        if not pts: return [indent + '[]']
        lines = [indent + '[']
        for i in range(0, len(pts), 4):
            lines.append(indent + '    ' + ' '.join(f"new({p[0]:.4f}f, {p[1]:.4f}f, {p[2]:.4f}f)," for p in pts[i:i + 4]))
        lines.append(indent + ']')
        return lines
    for n in R.NAMES:
        h = hulls.get(n)
        if h is None or not h['parts']: out.append(f'        [],   // {n}'); continue
        out.append(f'        [   // {n}')
        for part in h['parts']:
            out.append(f'            new("{part["binding"]}",')
            hb = block(part['handle'], '                '); hb[-1] += ','
            bb = block(part['blade'], '                '); bb[-1] += '),'
            out.extend(hb); out.extend(bb)
        out.append('        ],')
    out.append('    ];')
    out.append('''
    /// <summary>The knife's hulls per part, or an empty array for a knife without any.</summary>
    public static Part[] Parts(int variant) =>
        variant >= 0 && variant < s_parts.Length ? s_parts[variant] : [];
}''')
    open(HULLS_CS, 'w').write('\n'.join(out) + '\n')

def rewrite_handle_table(cs, hulls):
    a = cs.index('    static readonly Vector3[] s_handleDirections = [')
    b = cs.index('    ];', a) + len('    ];')
    lines = ['    static readonly Vector3[] s_handleDirections = [']
    for n in R.NAMES:
        h = hulls.get(n)
        if n in KEEP or h is None or h['axis'] is None:
            x, y, z = KEEP.get(n, (0.0, 0.0, 1.0)); lines.append(f"        new({x:.4f}f, {y:.4f}f, {z:.4f}f),".ljust(46) + f"// {n}  (kept)")
        else:
            x, y, z = h['axis']; lines.append(f"        new({x:.4f}f, {y:.4f}f, {z:.4f}f),".ljust(46) + f"// {n}  ({h['handle_vs_whole_deg']:.0f} deg off the whole knife)")
    lines.append('    ];')
    return cs[:a] + '\n'.join(lines) + cs[b:]

if __name__ == '__main__':
    cs = open(RENDERER).read()
    fr = grip_fractions(cs)
    hulls = {}
    for n in R.NAMES:
        if n in KEEP: continue
        hulls[n] = analyse(n, fr.get(n, 0.235))
        h = hulls[n]
        print(f"{n:<10} handle axis {h['handle_vs_whole_deg']:5.1f} deg off the whole knife; parts " +
              ', '.join(f"{p['binding']}(h{len(p['handle'])}/b{len(p['blade'])})" for p in h['parts']))
    json.dump(hulls, open(HULLS_JSON, 'w'), indent=1)
    write_cs(hulls)
    open(RENDERER, 'w').write(rewrite_handle_table(cs, hulls))
    print('wrote', HULLS_JSON, HULLS_CS, 'and s_handleDirections')
