name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - run: dotnet build ScCsgoKnives.sln -c Release
      - uses: actions/upload-artifact@v7
        with:
          name: ScCsgoKnives-scmod
          path: src/ScCsgoKnives/bin/Release/ScCsgoKnives.scmod

